sonar.projectKey=fr.nirahtech.devops-demo
sonar.host.url=http://172.17.0.1:9000
sonar.token=sqa_8c5b3e5039284bd6e1d8f30997d3855a07918258
sonar.java.binaries=target/classes
sonar.exclusions=**.db,**.yaml,**.properties
